SneakersWebsite/SneakersWebsite/Models/ContactFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Models
{
    public class ContactFormModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }

    }
}

SneakersWebsite/SneakersWebsite/Models/EmailAddress.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Models
{
    public class EmailAddress
    {
        public string Name { get; set; }
        public string Address { get; set; }
    }
}

SneakersWebsite/SneakersWebsite/Models/EmailMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Models
{
    public class EmailMessage
    {
        public List<EmailAddress> ToAddresses { get; set; } = new List<EmailAddress>();
        public List<EmailAddress> FromAddresses { get; set; } = new List<EmailAddress>();
        public string Subject { get; set; }
        public string Content { get; set; }
    }

}

SneakersWebsite/SneakersWebsite/Models/EmailServerConfiguration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Models
{
    public class EmailServerConfiguration
    {
        public EmailServerConfiguration(int _smtpPort = 465)
        {
            SmtpPort = _smtpPort;
        }

        public string SmtpServer { get; set; }
        public int SmtpPort { get; }
        public string SmtpUsername { get; set; }
        public string SmtpPassword { get; set; }
    }
}

SneakersWebsite/SneakersWebsite/Models/ErrorViewModel.cs
using System;

namespace SneakersWebsite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SneakersWebsite/SneakersWebsite/Models/IEmailService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Models
{
    public interface IEmailService
    {
        void Send(EmailMessage message);
    }
}

SneakersWebsite/SneakersWebsite/Models/MailKitEmailService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MimeKit;

namespace SneakersWebsite.Models
{
    public class MailKitEmailService : IEmailService
    {
        private readonly EmailServerConfiguration _econfig;

        public MailKitEmailService(EmailServerConfiguration config)
        {
            _econfig = config;
        }
        public void Send(EmailMessage msg)
        {
            var message = new MimeMessage();
            message.To.AddRange(msg.ToAddresses.Select(x => new MailboxAddress(x.Name, x.Address)));
            message.From.AddRange(msg.FromAddresses.Select(x => new MailboxAddress(x.Name, x.Address)));

            message.Subject = msg.Subject;

            message.Body = new TextPart("plain")
            {
                Text = msg.Content
            };

            using (var client = new MailKit.Net.Smtp.SmtpClient())
            {
                client.Connect(_econfig.SmtpServer, _econfig.SmtpPort);
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                client.Authenticate(_econfig.SmtpUsername, _econfig.SmtpPassword);

                client.Send(message);
                client.Disconnect(true);
            }
        }
    }
}

SneakersWebsite/SneakersWebsite/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SneakersWebsite.Models;

namespace SneakersWebsite.Controllers
{

    //https://nickolasfisher.com/blog/How-To-Make-a-Basic-Working-Contact-Form-With-ASP-NET-Core-MVC-and-MailKit
    public class ContactController : Controller
    {
        private EmailAddress FromAndToEmailAddress;
        private IEmailService EmailService;


        public ContactController(EmailAddress _fromAddress, IEmailService _emailService)
        {
            FromAndToEmailAddress = _fromAddress;
            EmailService = _emailService;
        }


        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }



        public IActionResult Contact(ContactFormModel viewModel)
        {
            if (ModelState.IsValid)
            {
                EmailMessage msgToSend = new EmailMessage
                {
                    FromAddresses = new List<EmailAddress> { FromAndToEmailAddress },
                    ToAddresses = new List<EmailAddress> { FromAndToEmailAddress },
                    Content = $"Here is your message: Name: {viewModel.Name}, " +
                    $"Email: {viewModel.Email}, Message: {viewModel.Message}",
                    Subject = "Contact Form Message "
                };

                EmailService.Send(msgToSend);
                return RedirectToAction("Success");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

SneakersWebsite/SneakersWebsite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SneakersWebsite.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SneakersWebsite/SneakersWebsite/Controllers/ShoePagesController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SneakersWebsite.Controllers
{
    public class ShoePagesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AdidasHu()
        {
            return View();
        }

        public IActionResult BlazerMidSacai()
        {
            return View();
        }

        public IActionResult YeezyBeluga()
        {
            return View();
        }

        public IActionResult BredToe()
        {
            return View();
        }

        public IActionResult YeezyZebra()
        {
            return View();
        }
        public IActionResult UniversityBlue()
        {
            return View();
        }

        public IActionResult PineGreen()
        {
            return View();
        }

        public IActionResult RoyalToe()
        {
            return View();
        }

        public IActionResult JordanSb()
        {
            return View();
        }

    }
}

SneakersWebsite/SneakersWebsite/Controllers/ShoesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SneakersWebsite.Controllers
{
    public class ShoesController : Controller
    {
        public IActionResult AllShoes()
        {
            return View();
        }

        
    }
}

SneakersWebsite/SneakersWebsite/Views/Contact/Contact.cshtml
@model SneakersWebsite.Models.ContactFormModel

@{
    ViewData["Title"] = "Contact Us";
}

<br />
<h1>Contact Us!</h1>

<hr />

<div class="col-md-5">
<form class="form" asp-action="Contact" asp-controller="Contact" method="post">
    @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
    <div class="form-outline mb-4">
        <input type="text" asp-for="Name" class="form-control" />
        <label asp-for="Name" class="form-label"></label>
        @*<span asp-validation-for="Name" class="text-danger"></span>*@
    </div>
    <div class="form-outline mb-4 ">
        <input type="email" asp-for="Email" class="form-control" />
        <label asp-for="Email" class="form-label"></label>
        
        @*<span asp-validation-for="Email" class="text-danger"></span>*@
    </div>
    <div class="form-outline mb-4">
        <textarea asp-for="Message" class="form-control"></textarea>
        <label asp-for="Message" class="form-label"></label>
        
        @*<span asp-validation-for="Message" class="text-danger"></span>*@
    </div>
    <div class="form-group">
        <input type="submit" value="Send Message!" class="btn btn-primary" />
    </div>
</form>
<br />
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2999.04935315976!2d-111.9670134843507!3d41.264261311581365!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87530c1bdc07b2ad%3A0x4fb3dacbdd584e8b!2sOgden-Weber%20Technical%20College!5e0!3m2!1sen!2sus!4v1624378382300!5m2!1sen!2sus" 
width="1400" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>

<br />
<br />


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SneakersWebsite/SneakersWebsite/Views/Contact/Success.cshtml
@{ 
    ViewData["Title"] = "Message Sent";
}

<h1>Success!</h1>

<h3>Your message has been sent. Thank you for contacting us.</h3>

SneakersWebsite/SneakersWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="page-container">
    <div id="content-wrap">
        <br />
<div class="text-center">
    <h1 style="font-size:50px;">Kicks'R'Us</h1>
    <h3>The #1 place to shop for limited sneakers!</h3>
</div>

<div class="hero-image">
    @*<div class="hero-text">
        <h1 style="font-size:50px">Kicks'R'Us</h1>
        <h3>The #1 place for sneaker connoisseurs.</h3>
    </div>*@
</div>

<br />
<hr style="height:3px;">
<br />
<div class="text-center">
    <h3>Best Sellers</h3>
</div>


<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img
        src="/images/bredtoes.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High Bred Toe</h5>
        <p class="card-text">
          Combining elements of three certified classic AJ1’s, the 2018 Jordan 1 Retro High Bred Toe is like the Coachella lineup of OG 1s.
            Coming in gym red, black, and summit white, with red on the toe box, outsole, and wrapping around the ankle and heel, white side panels and midsole 
            and black covering the rest of the sneaker, it’s a perfectly balanced mash-up of the Banned, Chicago,
            and Black Toe all in one. Originally releasing in February of 2018, the Bred toe has been one of the most popular sneakers.
        </p>
      </div>
      
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img
        src="/images/nikejordansoffwhite.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High Off-White University Blue</h5>
        <p class="card-text">
          Time for some Tobacco Road vibes with these Jordan 1 Retro Off-Whites. Also known as the “UNC” editions, these Jordan 1s are the third colorway designed by Virgil Abloh and made
            in collaboration with his Off-White label. The sneakers come in a white, dark powder blue and cone colorway, with a white and blue deconstructed leather upper and Off-White detailing throughout.
            If you’re a fan of Virgil Abloh’s work and want to rep Off-White, this pair is another must-have.
        </p>
      </div>
    
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img
        src="/images/yeezyzebra.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Adidas Yeezy Boost 350 V2 Zebra</h5>
        <p class="card-text">
          Adidas is back with their latest Yeezy Boost 350 V2. Fresh off the heels of NBA All-Star Weekend, these Yeezy's are nicknamed the "Zebras,"
            and come in a classic white, black and red color scheme. Sporting a white-based Primeknit upper with black accents giving off a Zebra stripe vibe, 
            “SPLY-350” displayed across the sides in red finished off by a translucent BOOST cushioned sole. 
            To date they are the most limited adidas Yeezy release and have instantly become one of the most popular colorways.
            Their release date is set for February 25th, 2017. Retail is set at $220 and they will only be available in men’s sizing, no love for infants from Yeezus this time around. On June 24th, 
            adidas will re-release the coveted “Zebras,” giving fans worldwide one more shot at obtaining one of 2017s most popular kicks. 
        </p>
      </div>
      
    </div>
  </div>
</div>

        <br />
        <br />
       
</div>
</div>

SneakersWebsite/SneakersWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kicks'R'Us</title>
    <link rel="icon" href="~/images/icon.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet" />
    <link rel="stylesheet" href="~/css/main.css" />

</head>
<body>
    <header>
        <!--<nav class="main-navbar navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kicks'R'Us</a>
                <button class="navbar-toggler text-black-50" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">-->
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>*@
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shoes" asp-action="Shoes">Shoes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contact">Contact</a>
                        </li>-->
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    <!--</ul>
                </div>
            </div>
        </nav>-->

        <!-- Navbar -->
<nav class="main-navbar navbar navbar-expand-lg navbar-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" asp-action="Index" asp-controller="Home">
        <img
          src="/images/icon.png"
          height="25"
          alt=""
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" asp-action="AllShoes" asp-controller="Shoes">Shoes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-action="Contact" asp-controller="Contact">Contact</a>
        </li>
        
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
      <a class="text-reset me-3" href="#">
        <i class="fas fa-shopping-cart text-dark"></i>
      </a>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-center">
        <div>
            &copy; 2021 - Kicks'R'Us - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- MDB -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SneakersWebsite/SneakersWebsite/Views/ShoePages/AdidasHu.cshtml
@{
    ViewData["Title"] = "Adidas Hu NMD";
}

<br />
<br />
<div id="page-container">
    <div id="content-wrap">



        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="/images/SneakerImages/blackyellowhumanraces.jpg"
                         alt="Adidas NMD HU Pharrel Human Species Black"
                         class="rounded image-responsive"
                         style="height:600px;width:550px;" />
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Adidas Hu NMD</h1>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-12">
                            <span class="label label-primary">Limited</span>
                            <span class="monospaced">No. 1964523718</span>
                        </div>
                    </div> <!-- End Row-->

                    <div class="row">
                        <div class="col-md-12">
                            <p class="description">
                                In collaboration with Adidas, Pharrel dropped these kicks for the world. Based on the NMD base, these are sure to turn heads.
                            </p>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-12 bottom-rule">
                            <h2 class="product-price">$250</h2>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-lg btn-brand btn-full-width">
                                Add to Cart!
                            </button>
                        </div>
                    </div> <!-- End Row-->
                </div>
            </div>
        </div>

    </div>
</div>

SneakersWebsite/SneakersWebsite/Views/ShoePages/BlazerMidSacai.cshtml
@{
    ViewData["Title"] = "Nike Blazer Mid Sacai Snow Beach";
}

<br />
<br />
<div id="page-container">
    <div id="content-wrap">



        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="/images/SneakerImages/nikesacai.jpg"
                         alt="Nike Blazer Mid Sacai Snow Beach"
                         class="image-responsive"
                         style="height:600px;width:550px;" />
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Nike Blazer Mid Sacai Snow Beach</h1>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-12">
                            <span class="label label-primary">Limited</span>
                            <span class="monospaced">No. 19645237896</span>
                        </div>
                    </div> <!-- End Row-->

                    <div class="row">
                        <div class="col-md-12">
                            <p class="description">
                                Hit your nearest beach in style while rocking the Nike Blazer High sacai Snow Beach. This Blazer High comes with a yellow upper plus blue accents, 
                                red Nike “Swoosh”, blue Nike “Swoosh”, white midsole, and white sole. 
                            </p>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-12 bottom-rule">
                            <h2 class="product-price">$450</h2>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-lg btn-brand btn-full-width">
                                Add to Cart!
                            </button>
                        </div>
                    </div> <!-- End Row-->
                </div>
            </div>
        </div>

    </div>
</div>

SneakersWebsite/SneakersWebsite/Views/ShoePages/BredToe.cshtml
@{
    ViewData["Title"] = "Jordan 1 Retro High Bred Toe";
}

<br />
<br />
<div id="page-container">
    <div id="content-wrap">



        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="/images/bredtoes.jpg"
                         alt="Jordan 1 Retro High Bred Toe"
                         class=" rounded image-responsive"
                         style="height:600px;width:550px;" />
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Jordan 1 Retro High Bred Toe</h1>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-12">
                            <span class="label label-primary">Limited</span>
                            <span class="monospaced">No. 19645237742</span>
                        </div>
                    </div> <!-- End Row-->

                    <div class="row">
                        <div class="col-md-12">
                            <p class="description">
                               Combining elements of three certified classic AJ1’s, the 2018 Jordan 1 Retro High Bred Toe is like the Coachella lineup of OG 1s. Coming in gym red, black, and summit white, with red on the toe box, outsole, and wrapping around the ankle and heel, white side panels and midsole and black covering the rest of the sneaker,
                               it’s a perfectly balanced mash-up of the Banned, Chicago, and Black Toe all in one. 
                            </p>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-12 bottom-rule">
                            <h2 class="product-price">$750</h2>
                        </div>
                    </div> <!--End Row-->

                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-lg btn-brand btn-full-width">
                                Add to Cart!
                            </button>
                        </div>
                    </div> <!-- End Row-->
                </div>
            </div>
        </div>

    </div>
</div>

SneakersWebsite/SneakersWebsite/Views/Shoes/AllShoes.cshtml
@{
    ViewData["Title"] = "All Shoes";
}
<div id="page-container">
    <div id="content-wrap">

 <br />
 <h1 class="text-center">All our Shoes</h1>
  <br />
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card">
      <img
        src="/images/SneakerImages/blackyellowhumanraces.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Adidas NMD HU Pharrel Human Species Black</h5>
        <p class="card-text">
          click to see more about these kicks!
        </p>
          <a asp-action="AdidasHu" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img
        src="/images/SneakerImages/nikesacai.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Nike Blazer Mid Sacai Snow Beach</h5>
        <p class="card-text">
         click to see more about these kicks!
        </p>
          <a asp-action="BlazerMidSacai" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img
        src="/images/SneakerImages/yeezybelugav1.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Adidas Yeezy Boost 350 V2 Beluga</h5>
        <p class="card-text">
        click to see more about these kicks!
        </p>
          <a asp-action="YeezyBeluga" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img
        src="/images/bredtoes.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High Bred Toe</h5>
        <p class="card-text">
        click to see more about these kicks!
        </p>
          <a asp-action="BredToe" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
   <div class="col">
    <div class="card">
      <img
        src="/images/yeezyzebra.jpg" 
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Adidas Yeezy Boost 350 V2 Zebra</h5>
        <p class="card-text">
         click to see more about these kicks!
        </p>
          <a asp-action="YeezyZebra" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
   <div class="col">
    <div class="card">
      <img
        src="/images/nikejordansoffwhite.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High Off-White University Blue</h5>
        <p class="card-text">
         click to see more about these kicks!
        </p>
          <a asp-action="UniversityBlue" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
     <div class="col">
    <div class="card">
      <img
        src="/images/SneakerImages/jordan1pinegreen.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High Pine Green Black</h5>
        <p class="card-text">
          click to see more about these kicks!
        </p>
          <a asp-action="PineGreen" asp-controller="ShoePages" class="btn btn-dark">View product details</a>
      </div>
    </div>
  </div>
     <div class="col">
    <div class="card">
      <img
        src="/images/SneakerImages/jordan1highroyal.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High Royal Toe</h5>
        <p class="card-text">
     click to see more about these kicks!
        </p>
          <a asp-action="RoyalToe" asp-controller="ShoePages" class="btn btn-dark">View Product details</a>
      </div>
    </div>
  </div>
     <div class="col">
    <div class="card">
      <img
        src="/images/SneakerImages/SBtoChicago2.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Jordan 1 Retro High OG Defiant SB LA to Chicago</h5>
        <p class="card-text">
          Drop some magic on the haters after copping the Jordan 1 Retro High OG Defiant SB Lakers.
            This AJ 1 SB comes with a white upper plus blue and yellow accents, yellow Nike "Swoosh", white midsole, and a black sole.
        </p>
          <a asp-action="JordanSb" asp-controller="ShoePages" class="btn btn-dark">view product details</a>
      </div>
    </div>
   </div>
   </div>

   </div>

</div>